#!/usr/bin/env sh

POWER_CAMPUS_USERNAME=$POWER_CAMPUS_USERNAME
POWER_CAMPUS_PASSWORD=$POWER_CAMPUS_PASSWORD

DB_NAME=$DB_NAME

ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
REFRESHER_TOKEN_SECRET=$REFRESHER_TOKEN_SECRET
BCRYPT_PEPPER=$BCRYPT_PEPPER
SALT_ROUNDS=$SALT_ROUNDS
ENV=$ENV
URL=$URL